name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-12

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4.1'

    - name: Build
      uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        project: Example/Example.xcodeproj
        scheme: Example
        destination: "platform=iOS Simulator,name=iPhone 11"
        action: test

    - name: Run tests
      uses: sersoft-gmbh/xcodebuild-action@v2
      with:
        project: Example/Example.xcodeproj
        scheme: Example
        destination: "platform=iOS Simulator,name=iPhone 11"
        action: test