
name: Run Tests

on:
  push:
    branches: [ develop, main, feature/* ]
  pull_request:
    branches: [ develop, main, feature/* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'

      - name: Run Tests
        run: bundle exec xcodebuild build test -proj Example/KeychainPasswordStoreExample.xcodeproj -scheme KeychainPasswordStoreExample -destination 'platform=iOS Simulator,name=iPhone 14'