name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_tests_and_code_coverage:
    name: Run Tests and Code Coverage
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0.1'
      - name: Run Tests
        run: xcodebuild build test -project Example/KeychainPasswordStoreExample.xcodeproj -scheme KeychainPasswordStoreExample -destination 'OS=26.0,name=iPhone 17' -resultBundlePath /Users/runner/Library/Developer/Xcode/KeychainPasswordStore/ResultBundle/keychainPasswordStore_result
      - name: Install XCResultParser
        run: brew install a7ex/homebrew-formulae/xcresultparser
      - name: Parse XCResult For CodeCov
        run: xcresultparser -o cobertura /Users/runner/Library/Developer/Xcode/KeychainPasswordStore/ResultBundle/keychainPasswordStore_result.xcresult > /Users/runner/Library/Developer/Xcode/KeychainPasswordStore/ResultBundle/coverage.xml
      - name: Upload Coverage XML to CodeCov
        uses: codecov/codecov-action@v5
        with:
          files: /Users/runner/Library/Developer/Xcode/KeychainPasswordStore/ResultBundle/coverage.xml
          plugin: xcode
          token: ${{ secrets.CODECOV_TOKEN }}
      
      
      # - name: Upload Xcode Code Coverage Report to CodeCov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     fail_ci_if_error: true
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     verbose: true
      #     xcode: true
      #     xcode_archive_path: /Users/runner/Library/Developer/Xcode/KeychainPasswordStore/ResultBundle/keychainPasswordStore_result.xcresult